language: node_js
node_js:
  - "stable"

script:
  - npm run build

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: true
  on:
    branch: develop
